server:
  port: 8081

lolsearcher:
  kafka:
    bootstrap-server: ${kafka.bootstrap-server}
  riot_api_key: ${riot_api_key}
  jwt:
    secret: gsgsg
  webclient:
    kr-base-url: https://kr.api.riotgames.com
    asia-base-url: https://asia.api.riotgames.com
  redis:
    host: ${redis.host}
    port: ${redis.port}
  cache:
    summoner:
      ttl: 600
    rank:
      ttl: 3600
    match:
      ttl: 3600  # 1h
    ingame:
      ttl: 120 # 2min
    abuser:
      ttl: 1 # 1day

logging:
  file:
    name: lolsearcher.log
    path: C:\Users\ForYouCom\Desktop\LOLSEARCHER